# Site settings
title: Artist
email: joy@joythesky.art
url: https://www.joythesky.art
description: "Júlia es una artista excepcionalmente talentosa y apasionada que ha demostrado una habilidad impresionante para crear pinturas y cuadros de gran calidad. Sus obras son hermosas, evocadoras y llenas de expresividad, y muestran una comprensión profunda de los principios fundamentales del arte y la estética. Como estudiante de bellas artes en la universidad, Júlia ha adquirido una amplia gama de habilidades técnicas y conocimientos teóricos que le han permitido perfeccionar aún más su oficio. Su creatividad y su habilidad para experimentar con diferentes técnicas y materiales han llevado a la creación de obras verdaderamente únicas y originales. En resumen, Júlia es una artista con un gran talento y una pasión inquebrantable por el arte. Su capacidad para crear obras de arte que despiertan emociones y transmiten significado es verdaderamente impresionante y seguramente la llevará a tener éxito en su carrera artística."
keywords: "arte, diseño, art, design, digital art, images, pictures"
skills: "Fine Arts degree - Graphic Artist - Best Artist"
meta_author: Segura Julia
icon: img/favicon.ico
whatsapp_icon: img/profile256.png
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Joy

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: JoyTheSky
  location: Spain
  social: Around the Web
  credits: Joy

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/joythesky
  - title: tiktok
    url:
  - title: instagram
    url: https://www.instagram.com/joythesky

# Postal address (add as many lines as necessary)
address:
  - line: Spain
  - line: Spain

# Credits content
credits: 'Júlia es una artista excepcionalmente talentosa y apasionada que ha demostrado una habilidad impresionante para crear pinturas y cuadros de gran calidad. Sus obras son hermosas, evocadoras y llenas de expresividad, y muestran una comprensión profunda de los principios fundamentales del arte y la estética. Como estudiante de bellas artes en la universidad, Júlia ha adquirido una amplia gama de habilidades técnicas y conocimientos teóricos que le han permitido perfeccionar aún más su oficio. Su creatividad y su habilidad para experimentar con diferentes técnicas y materiales han llevado a la creación de obras verdaderamente únicas y originales. En resumen, Júlia es una artista con un gran talento y una pasión inquebrantable por el arte. Su capacidad para crear obras de arte que despiertan emociones y transmiten significado es verdaderamente impresionante y seguramente la llevará a tener éxito en su carrera artística.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
